version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - spotify-app
  api-server:
    image: api-server
    ports: 
      - "3001:3001"
    networks: 
      - spotify-app
networks:
  spotify-app:
    driver: bridge